APP_TITLE = "Дым Дым Казино"
DB_PATH = "database/app.db"
LOG_PATH = "log.txt"
DEFAULT_BALANCE = 5000
ASSETS_DIR = "assets"
SOUND_CLICK = "sounds/click.mp3"
SOUND_ROULETTE_SPIN = "sounds/roulette_spin.mp3"
SOUND_SLOTS_SPIN = "sounds/slots_spin.mp3"
SOUND_WIN = "sounds/win.mp3"
SOUND_LOSE = "sounds/lose.mp3"
WINDOW_WIDTH = 1920
WINDOW_HEIGHT = 1080